services:
  - type: web
    name: super-business-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: super-business-flutter-web
    env: static
    buildCommand: "git clone https://github.com/flutter/flutter.git -b stable && export PATH=\"$PATH:$(pwd)/flutter/bin\" && flutter config --enable-web && flutter build web --release"
    staticPublishPath: "./build/web"
    envVars:
      - key: FLUTTER_VERSION
        value: 3.16.0
