services:
  - type: web
    name: super-business-shop
    env: static
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    staticPublishPath: build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000 # 1 year cache
      - path: /index.html
        name: Cache-Control
        value: no-cache # Always fetch latest index
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
